/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import reader.*;
/**
 *
 * @author hasalp
 */
public class Client extends javax.swing.JFrame {

    Reader temperature, humidity;
    
    public Client() {
        initComponents();
        ReaderBuilder builder = new ReaderBuilder();
        temperature = builder.getReader("temperature");
        humidity = builder.getReader("humidity");
        temperature.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        subscribeTopicsTitle = new javax.swing.JLabel();
        resultField = new javax.swing.JTextField();
        temperatureButton = new javax.swing.JRadioButton();
        humidityButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        subscribeTopicsTitle.setText("Subscribe Topic:");

        resultField.setFont(new java.awt.Font("Noto Sans", 0, 48)); // NOI18N
        resultField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultField.setText("Null");

        buttonGroup.add(temperatureButton);
        temperatureButton.setSelected(true);
        temperatureButton.setText("Temperature");
        temperatureButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                temperatureButtonItemStateChanged(evt);
            }
        });

        buttonGroup.add(humidityButton);
        humidityButton.setText("Humidity");
        humidityButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                humidityButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subscribeTopicsTitle)
                        .addGap(18, 18, 18)
                        .addComponent(temperatureButton)
                        .addGap(18, 18, 18)
                        .addComponent(humidityButton)
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subscribeTopicsTitle)
                    .addComponent(temperatureButton)
                    .addComponent(humidityButton))
                .addGap(18, 18, 18)
                .addComponent(resultField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temperatureButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_temperatureButtonItemStateChanged
        if(temperatureButton.isSelected()){
            System.out.println("Temp ON Triggered");
            temperature.start();
        }else{
            System.out.println("Temp OFF Triggered");
            temperature.stop();
        }
    }//GEN-LAST:event_temperatureButtonItemStateChanged

    private void humidityButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_humidityButtonItemStateChanged
        if(humidityButton.isSelected()){
            System.out.println("Hum ON Triggered");
            humidity.start();
        }else{
            System.out.println("Hum OFF Triggered");
            humidity.stop();
        }
    }//GEN-LAST:event_humidityButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton humidityButton;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField resultField;
    private javax.swing.JLabel subscribeTopicsTitle;
    private javax.swing.JRadioButton temperatureButton;
    // End of variables declaration//GEN-END:variables
}
